eudaemo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from meals_app import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meals_app.urls')),
    path('', core_views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),  # <--
    path('admin/', admin.site.urls),
]

meals_app/urls.py
from django.urls import path
from . import views

app_name = "meals_app"

urlpatterns = [
    path('', views.home, name='home'),
    path('add_meal', views.add_meal, name='add_meal'),
    path('add_workout', views.add_workout, name='add_workout'),
    path('one_day', views.one_day, name='one_day'),
    path('one_workout', views.one_workout, name='one_workout'),
    path('add_book', views.add_book, name='add_book'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('single_meal', views.single_meal, name='single_meal'),
    path('google_meal', views.google_meal, name='google_meal'),
    path('single_workout', views.single_workout, name='single_workout'),
    path('google_workout', views.google_workout, name='google_workout'),
    path('google_book', views.google_book, name='google_book'),
]

meals_app/models.py
from django.db import models
# from django.contrib.auth.models import User
# from oauth2client.contrib.django_orm import FlowField


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    shopping_list = models.CharField(max_length=100000)
    ingredients = models.CharField(max_length=100000)
    instructions = models.CharField(max_length=100000)
    prep_time = models.CharField(max_length=10)
    cook_time = models.CharField(max_length=10)
    total_time = models.CharField(max_length=10)
    servings = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Workout(models.Model):
    workout = models.CharField(max_length=10000)

meals_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from googleapiclient.discovery import build
from django.contrib.auth.decorators import login_required
from oauth2client import file, client
import datetime
from datetime import datetime, timedelta, date
import random
from .models import Recipe, Workout
from django.shortcuts import get_object_or_404
from django.core import serializers
from django.http import JsonResponse


def home(request):
    return render(request, 'core/home.html')


def about(request):
    return render(request, 'core/about.html')


def contact(request):
    return render(request, 'core/contact.html')


def single_meal(request):
    return render(request, 'core/singleMeal.html')


def google_meal(request):
    return render(request, 'core/googleMeal.html')


def single_workout(request):
    return render(request, 'core/singleWorkout.html')


def google_workout(request):
    return render(request, 'core/googleWorkout.html')


def google_book(request):
    return render(request, 'core/googleBook.html')


@login_required
def add_meal(request):
    random_meal = random.randint(405, 605)
    meal_details = get_object_or_404(Recipe, pk=random_meal)
    # print(meal_details.name)
    # print(meal_details['shopping_list'])
    query = request.POST
    # print(query)
    print('this is the calDate')
    print((query['calDate']))
    time = query['calTime'].split(':')
    time[0] = str(int(time[0])+1)
    # print('time changed to')
    # print(time)
    # if i decide to add the  shopping list to the previous sunday this will be helpful
    # parsDate = query['calDate']
    # parsDate = parsDate.split('-')
    # print('parsDate is ' + parsDate[0])
    # print(datetime.datetime.today().weekday())
    # print(datetime.datetime(int(parsDate[0]), int(parsDate[1]), int(parsDate[2]), 9, 51, 47, 244794).weekday())
    social = request.user.social_auth.get(provider='google-oauth2')
    access_token = social.extra_data['access_token']
    credentials = client.AccessTokenCredentials(access_token, 'eudaemo')
    GMT_OFF = '-07:00'
    EVENT = {
        'summary': meal_details.name,
        'start': {'dateTime': str(query['calDate'])+'T' + query['calTime'] + ':00%s' % GMT_OFF},
        'end': {'dateTime': str(query['calDate'])+'T' + time[0] + ':' + time[1] + ':00%s' % GMT_OFF},
        'description': 'Shopping List: ' + meal_details.shopping_list + '\n \n' + 'Recipe: ' + meal_details.ingredients + '\n \n' + 'Directions' + meal_details.instructions
    }

    service = build('calendar', 'v3', credentials=credentials)
    event = service.events().insert(calendarId='primary', body=EVENT).execute()
    print(event)
    return render(request, 'core/home.html')
    # return JsonResponse({"access_token": social.extra_data['access_token']})


def one_day(request):
    random_meal = random.randint(405, 605)
    meal_details = get_object_or_404(Recipe, pk=random_meal)
    data = {'cook time': meal_details.cook_time, 'name': meal_details.name, 'shopping_list': meal_details.shopping_list, 'instructions': meal_details.instructions, 'prep_time': meal_details.prep_time, 'servings': meal_details.servings, 'recipe': meal_details.ingredients}
    return JsonResponse(data)


def one_workout(request):
    random_workout = random.randint(1, 62)
    workout_details = get_object_or_404(Workout, pk=random_workout)
    data = {'workout': workout_details.workout}
    return JsonResponse(data)


@login_required
def add_workout(request):
    # if request.user.is_authenticated:
        random_workout = random.randint(1, 62)
        workout_details = get_object_or_404(Workout, pk=random_workout)
        print(workout_details.workout)
        query = request.POST
        # print(query)
        print('this is the calDate')
        print((query['workoutCalDate']))
        time = query['workoutCalTime'].split(':')
        time[0] = str(int(time[0])+1)
        social = request.user.social_auth.get(provider='google-oauth2')
        access_token = social.extra_data['access_token']
        credentials = client.AccessTokenCredentials(access_token, 'eudaemo')
        GMT_OFF = '-07:00'
        EVENT = {
            'summary': "Today's Workout",
            'start': {'dateTime': str(query['workoutCalDate'])+'T' + query['workoutCalTime'] + ':00%s' % GMT_OFF},
            'end': {'dateTime': str(query['workoutCalDate'])+'T' + time[0] + ':' + time[1] + ':00%s' % GMT_OFF},
            'description': 'Workout: ' + workout_details.workout
        }
        service = build('calendar', 'v3', credentials=credentials)
        event = service.events().insert(calendarId='primary', body=EVENT).execute()
        print(event)
        return render(request, 'core/home.html')
    # else:
    #     return render(request, 'registration/login.html')


@login_required
def add_book(request):
    query = request.POST
    title = query['title']
    startDate = query['bookStartDate']
    bookFinishDate = query['bookFinishDate']
    frequency = query['reminderFrequency']
    pages = int(query['pages'])
    start = datetime.strptime(startDate, "%Y-%m-%d")
    # print('start date: ' + str(start))
    # print(start + timedelta(days=1)) to add days to start day
    # print(query['bookFinishDate'])
    finish = datetime.strptime(bookFinishDate, "%Y-%m-%d")
    totalTime = 0
    while start + timedelta(days=totalTime) != finish:
        totalTime += 1
    totalTime += 1
    # print(totalTime)
    PPD = pages/totalTime
    # print(PPD)
    better_date = str(start)
    # print('better date: ' + better_date)
    better_date = better_date.split(' ')
    # print('new better_date: ' + better_date[0])
    start_adding_goals = 0
    while start_adding_goals < totalTime + int(frequency):
        # day_adding_goal = start +timedelta(days=start_adding_goals)
        if start_adding_goals == 0:
            time = query['bookReminderTime'].split(':')
            time[0] = str(int(time[0])+1)
            social = request.user.social_auth.get(provider='google-oauth2')
            access_token = social.extra_data['access_token']
            credentials = client.AccessTokenCredentials(access_token, 'eudaemo')
            GMT_OFF = '-07:00'
            EVENT = {
                'summary': "Start reading " + title,
                'start': {'dateTime': str(query['bookStartDate'])+'T' + query['bookReminderTime'] + ':00%s' % GMT_OFF},
                'end': {'dateTime': str(query['bookStartDate'])+'T' + time[0] + ':' + time[1] + ':00%s' % GMT_OFF},
                'description': 'Today is the day you planned on starting to read the book ' + title + '. Good luck completing it before ' + bookFinishDate + "."
            }
            service = build('calendar', 'v3', credentials=credentials)
            event = service.events().insert(calendarId='primary', body=EVENT).execute()
            print(event)
            start_adding_goals = start_adding_goals + int(frequency)
        elif start_adding_goals >= totalTime:
            time = query['bookReminderTime'].split(':')
            time[0] = str(int(time[0])+1)
            social = request.user.social_auth.get(provider='google-oauth2')
            access_token = social.extra_data['access_token']
            credentials = client.AccessTokenCredentials(access_token, 'eudaemo')
            GMT_OFF = '-07:00'
            EVENT = {
                'summary': title + ' Finished',
                'start': {'dateTime': str(query['bookFinishDate'])+'T' + query['bookReminderTime'] + ':00%s' % GMT_OFF},
                'end': {'dateTime': str(query['bookFinishDate'])+'T' + time[0] + ':' + time[1] + ':00%s' % GMT_OFF},
                'description': 'If you are able to finish ' + title + ' before the end of today you have achieved your goal'
            }
            service = build('calendar', 'v3', credentials=credentials)
            event = service.events().insert(calendarId='primary', body=EVENT).execute()
            print(event)
            return render(request, 'core/home.html')
        elif start_adding_goals < totalTime:
            time = query['bookReminderTime'].split(':')
            time[0] = str(int(time[0])+1)
            page_goal = str(int(round(start_adding_goals * PPD)))
            google_date = start + timedelta(days=start_adding_goals)
            google_date = str(google_date).split(" ")
            google_date = google_date[0]
            print('google date is:' + google_date)
            social = request.user.social_auth.get(provider='google-oauth2')
            access_token = social.extra_data['access_token']
            credentials = client.AccessTokenCredentials(access_token, 'eudaemo')
            GMT_OFF = '-07:00'
            EVENT = {
                'summary': title + ' page: ' + page_goal,
                'start': {'dateTime': google_date+'T' + query['bookReminderTime'] + ':00%s' % GMT_OFF},
                'end': {'dateTime': google_date+'T' + time[0] + ':' + time[1] + ':00%s' % GMT_OFF},
                'description': 'If you are at page ' + page_goal + ' by the end of today, then you are on track for completing ' + title + ' before ' + bookFinishDate + '.'
            }
            service = build('calendar', 'v3', credentials=credentials)
            event = service.events().insert(calendarId='primary', body=EVENT).execute()
            print(event)
            start_adding_goals = start_adding_goals + int(frequency)
    return render(request, 'core/home.html')

meals_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Eudaemo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'meals_app/styles.css' %}">
    <link rel="icon" href="{% static 'meals_app/logo.png' %}">

</head>
<body>
<h1>Eudaemo</h1>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'meals_app:home' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'meals_app:about' %}">About<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'meals_app:contact' %}">Contact<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          How to
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'meals_app:single_meal' %}">Get a single random recipe</a>
          <a class="dropdown-item" href="{% url 'meals_app:google_meal' %}">Add a meal to your google calendar</a>
          <a class="dropdown-item" href="{% url 'meals_app:single_workout' %}">Get a workout for the day</a>
          <a class="dropdown-item" href="{% url 'meals_app:google_workout' %}">Add a workout to my google calendar</a>
          <a class="dropdown-item" href="{% url 'meals_app:google_book'  %}">Add book goals to my google calendar</a>
        </div>
      </li>
       <li class="nav-item">
        <a class="btn btn-primary"  id='google_login' href="{%if user.is_authenticated %} {% url 'logout' %} {% else %} {% url 'social:begin' 'google-oauth2' %} {% endif %}">{% if user.is_authenticated %} logout {% else %} login with google {% endif %}</a>
      </li>
    </ul>
  </div>
</nav>

{% block login %}
{% endblock %}
{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>