eudaemo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from meals_app import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meals_app.urls')),
    path('', core_views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),  # <--
    path('admin/', admin.site.urls),
]

meals_app/urls.py
from django.urls import path
from . import views

app_name = "meals_app"

urlpatterns = [
    path('', views.home, name='home'),
    path('add_meal', views.add_meal, name='add_meal'),
    path('add_workout', views.add_workout, name='add_workout'),
    path('one_day', views.one_day, name='one_day'),
    path('one_workout', views.one_workout, name='one_workout'),
    path('add_book', views.add_book, name='add_book'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('single_meal', views.single_meal, name='single_meal'),
    path('google_meal', views.google_meal, name='google_meal'),
    path('single_workout', views.single_workout, name='single_workout'),
    path('google_workout', views.google_workout, name='google_workout'),
    path('google_book', views.google_book, name='google_book'),
]

meals_app/models.py
from django.db import models
# from django.contrib.auth.models import User
# from oauth2client.contrib.django_orm import FlowField


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    shopping_list = models.CharField(max_length=100000)
    ingredients = models.CharField(max_length=100000)
    instructions = models.CharField(max_length=100000)
    prep_time = models.CharField(max_length=10)
    cook_time = models.CharField(max_length=10)
    total_time = models.CharField(max_length=10)
    servings = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Workout(models.Model):
    workout = models.CharField(max_length=10000)

meals_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from googleapiclient.discovery import build
from django.contrib.auth.decorators import login_required
from oauth2client import file, client
import datetime
from datetime import datetime, timedelta, date
import random
from .models import Recipe, Workout
from django.shortcuts import get_object_or_404
from django.core import serializers
from django.http import JsonResponse


def home(request):
    return render(request, 'core/home.html')


def about(request):
    return render(request, 'core/about.html')


def contact(request):
    return render(request, 'core/contact.html')


def single_meal(request):
    return render(request, 'core/singleMeal.html')


def google_meal(request):
    return render(request, 'core/googleMeal.html')


def single_workout(request):
    return render(request, 'core/singleWorkout.html')


def google_workout(request):
    return render(request, 'core/googleWorkout.html')


def google_book(request):
    return render(request, 'core/googleBook.html')


@login_required
def add_meal(request):
    random_meal = random.randint(405, 605)
    meal_details = get_object_or_404(Recipe, pk=random_meal)
    # print(meal_details.name)
    # print(meal_details['shopping_list'])
    query = request.POST
    # print(query)
    print('this is the calDate')
    print((query['calDate']))
    time = query['calTime'].split(':')
    time[0] = str(int(time[0])+1)
    # print('time changed to')
    # print(time)
    # if i decide to add the  shopping list to the previous sunday this will be helpful
    # parsDate = query['calDate']
    # parsDate = parsDate.split('-')
    # print('parsDate is ' + parsDate[0])
    # print(datetime.datetime.today().weekday())
    # print(datetime.datetime(int(parsDate[0]), int(parsDate[1]), int(parsDate[2]), 9, 51, 47, 244794).weekday())
    social = request.user.social_auth.get(provider='google-oauth2')
    access_token = social.extra_data['access_token']
    credentials = client.AccessTokenCredentials(access_token, 'eudaemo')
    GMT_OFF = '-07:00'
    EVENT = {
        'summary': meal_details.name,
        'start': {'dateTime': str(query['calDate'])+'T' + query['calTime'] + ':00%s' % GMT_OFF},
        'end': {'dateTime': str(query['calDate'])+'T' + time[0] + ':' + time[1] + ':00%s' % GMT_OFF},
        'description': 'Shopping List: ' + meal_details.shopping_list + '\n \n' + 'Recipe: ' + meal_details.ingredients + '\n \n' + 'Directions' + meal_details.instructions
    }

    service = build('calendar', 'v3', credentials=credentials)
    event = service.events().insert(calendarId='primary', body=EVENT).execute()
    print(event)
    return render(request, 'core/home.html')
    # return JsonResponse({"access_token": social.extra_data['access_token']})


def one_day(request):
    random_meal = random.randint(405, 605)
    meal_details = get_object_or_404(Recipe, pk=random_meal)
    data = {'cook time': meal_details.cook_time, 'name': meal_details.name, 'shopping_list': meal_details.shopping_list, 'instructions': meal_details.instructions, 'prep_time': meal_details.prep_time, 'servings': meal_details.servings, 'recipe': meal_details.ingredients}
    return JsonResponse(data)


def one_workout(request):
    random_workout = random.randint(1, 62)
    workout_details = get_object_or_404(Workout, pk=random_workout)
    data = {'workout': workout_details.workout}
    return JsonResponse(data)


@login_required
def add_workout(request):
    # if request.user.is_authenticated:
        random_workout = random.randint(1, 62)
        workout_details = get_object_or_404(Workout, pk=random_workout)
        print(workout_details.workout)
        query = request.POST
        # print(query)
        print('this is the calDate')
        print((query['workoutCalDate']))
        time = query['workoutCalTime'].split(':')
        time[0] = str(int(time[0])+1)
        social = request.user.social_auth.get(provider='google-oauth2')
        access_token = social.extra_data['access_token']
        credentials = client.AccessTokenCredentials(access_token, 'eudaemo')
        GMT_OFF = '-07:00'
        EVENT = {
            'summary': "Today's Workout",
            'start': {'dateTime': str(query['workoutCalDate'])+'T' + query['workoutCalTime'] + ':00%s' % GMT_OFF},
            'end': {'dateTime': str(query['workoutCalDate'])+'T' + time[0] + ':' + time[1] + ':00%s' % GMT_OFF},
            'description': 'Workout: ' + workout_details.workout
        }
        service = build('calendar', 'v3', credentials=credentials)
        event = service.events().insert(calendarId='primary', body=EVENT).execute()
        print(event)
        return render(request, 'core/home.html')
    # else:
    #     return render(request, 'registration/login.html')


@login_required
def add_book(request):
    query = request.POST
    title = query['title']
    startDate = query['bookStartDate']
    bookFinishDate = query['bookFinishDate']
    frequency = query['reminderFrequency']
    pages = int(query['pages'])
    start = datetime.strptime(startDate, "%Y-%m-%d")
    # print('start date: ' + str(start))
    # print(start + timedelta(days=1)) to add days to start day
    # print(query['bookFinishDate'])
    finish = datetime.strptime(bookFinishDate, "%Y-%m-%d")
    totalTime = 0
    while start + timedelta(days=totalTime) != finish:
        totalTime += 1
    totalTime += 1
    # print(totalTime)
    PPD = pages/totalTime
    # print(PPD)
    better_date = str(start)
    # print('better date: ' + better_date)
    better_date = better_date.split(' ')
    # print('new better_date: ' + better_date[0])
    start_adding_goals = 0
    while start_adding_goals < totalTime + int(frequency):
        # day_adding_goal = start +timedelta(days=start_adding_goals)
        if start_adding_goals == 0:
            time = query['bookReminderTime'].split(':')
            time[0] = str(int(time[0])+1)
            social = request.user.social_auth.get(provider='google-oauth2')
            access_token = social.extra_data['access_token']
            credentials = client.AccessTokenCredentials(access_token, 'eudaemo')
            GMT_OFF = '-07:00'
            EVENT = {
                'summary': "Start reading " + title,
                'start': {'dateTime': str(query['bookStartDate'])+'T' + query['bookReminderTime'] + ':00%s' % GMT_OFF},
                'end': {'dateTime': str(query['bookStartDate'])+'T' + time[0] + ':' + time[1] + ':00%s' % GMT_OFF},
                'description': 'Today is the day you planned on starting to read the book ' + title + '. Good luck completing it before ' + bookFinishDate + "."
            }
            service = build('calendar', 'v3', credentials=credentials)
            event = service.events().insert(calendarId='primary', body=EVENT).execute()
            print(event)
            start_adding_goals = start_adding_goals + int(frequency)
        elif start_adding_goals >= totalTime:
            time = query['bookReminderTime'].split(':')
            time[0] = str(int(time[0])+1)
            social = request.user.social_auth.get(provider='google-oauth2')
            access_token = social.extra_data['access_token']
            credentials = client.AccessTokenCredentials(access_token, 'eudaemo')
            GMT_OFF = '-07:00'
            EVENT = {
                'summary': title + ' Finished',
                'start': {'dateTime': str(query['bookFinishDate'])+'T' + query['bookReminderTime'] + ':00%s' % GMT_OFF},
                'end': {'dateTime': str(query['bookFinishDate'])+'T' + time[0] + ':' + time[1] + ':00%s' % GMT_OFF},
                'description': 'If you are able to finish ' + title + ' before the end of today you have achieved your goal'
            }
            service = build('calendar', 'v3', credentials=credentials)
            event = service.events().insert(calendarId='primary', body=EVENT).execute()
            print(event)
            return render(request, 'core/home.html')
        elif start_adding_goals < totalTime:
            time = query['bookReminderTime'].split(':')
            time[0] = str(int(time[0])+1)
            page_goal = str(int(round(start_adding_goals * PPD)))
            google_date = start + timedelta(days=start_adding_goals)
            google_date = str(google_date).split(" ")
            google_date = google_date[0]
            print('google date is:' + google_date)
            social = request.user.social_auth.get(provider='google-oauth2')
            access_token = social.extra_data['access_token']
            credentials = client.AccessTokenCredentials(access_token, 'eudaemo')
            GMT_OFF = '-07:00'
            EVENT = {
                'summary': title + ' page: ' + page_goal,
                'start': {'dateTime': google_date+'T' + query['bookReminderTime'] + ':00%s' % GMT_OFF},
                'end': {'dateTime': google_date+'T' + time[0] + ':' + time[1] + ':00%s' % GMT_OFF},
                'description': 'If you are at page ' + page_goal + ' by the end of today, then you are on track for completing ' + title + ' before ' + bookFinishDate + '.'
            }
            service = build('calendar', 'v3', credentials=credentials)
            event = service.events().insert(calendarId='primary', body=EVENT).execute()
            print(event)
            start_adding_goals = start_adding_goals + int(frequency)
    return render(request, 'core/home.html')

meals_app/templates/core/about.html
{% extends 'base.html' %}
{% load static %}

{% block login %}
<h3>The Name Eudaemo</h3>
<p>Latin origins, eu: well or good and deamon: originally referred to a lesser deity or guiding spirit</p>
<br/>
<h3>The Motivation</h3>
<p>The Paradox of Choice, by Barry Schwartz's, shows you how today’s vast amount of choice makes you frustrated, less likely to choose, more likely to mess up, and less happy overall, before giving you concrete strategies and tips to ease the burden of decision-making</p>
<ul>
    <li>
        The more options you have, the harder it gets to decide, and to decide well.
    </li>
    <li>
        The more options you have, the less happy you will be, no matter what you decide on.
    </li>
    <li>
        Good enough is the best – become a satisfier.
    </li>
</ul>
<h3>The Book Portion</h3>
<p>Setting goals can be very helpful in getting where you want to go and having smaller goals along the way not only increases the likely hood of completion but also provides little ego boosts along the way.</p>
{% endblock %}

meals_app/templates/core/contact.html
{% extends 'base.html' %}
{% load static %}

{% block login %}
<h3>Contact</h3>
<p>If you have any issues or ideas for improvement while using this site, please contact me at hayes_mitchell@yahoo.com
I have </p>

{% endblock %}

meals_app/templates/core/googleBook.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<p>Reading is something that many people with they did more of. If you like to have things written down, this tool can
help you reach your reading goals. Enter the day you want to start reading a book, when you want to complete the book by,
the title of the book, how many pages are in the book, and how frequently you want to have reminders added to your google calendar.
In your google calendar, on the start date, it will remind you that you wanted to start reading the book that day and,
    if you pick a frequency of 7 days, every 7 days there will be a reminder in your calendar with the page number that you should
be on before the end of the day if you want to keep pace to finish the book by your goal date.</p>
{% endblock%}

meals_app/templates/core/googleMeal.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<p>The best way to get a recipe is to add it to your google calendar. Just pick the day above the <button>Click</button>
    in the Eat section. Pick a time you would like it to be entered into your calendar and click the button. Check your
    google calendar and a random meal will be added to your calendar with a shopping list, recipe and directions to make the dish.</p>
{% endblock%}

meals_app/templates/core/googleWorkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<p> Getting a workout into your google calendar is very easy. Under the Exercise section, enter a day and a time you
want to Workout and press the <button>Click</button> button</p>
{% endblock%}

meals_app/templates/core/home.html
{% extends 'base.html' %}
{% load static %}

{% block login %}




<div>


        {% if user.is_authenticated %}
        <h3>Welcome {{ user.username}}!</h3><br/>
        {% else %}
        <h3>Welcome!</h3><br/><br/>

        {% endif %}

</div>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <h3>Eat</h3>
            <img src="{% static 'meals_app/dinner-party.jpg' %}"  >
            <h4>Live longer by preparing healthy meals.</h4>
            <p ><button id="One_Meal">Click Me</button> to get a random recipe.</p>
                <ul id="one_meal_lists">
                </ul>

            <form action="{% url 'meals_app:add_meal' %}" method="post">
                {% csrf_token %}
                <input type="date" name="calDate">
                <input type="time" name="calTime" value="20:00">
                <p><input type="submit" value="Click"> to add a meal to your google calendar</p>
            </form>
            <script src="{% static 'meals_app/oneMeal.js' %}"></script>
        </div>


        <div class="col-sm-4">
            <h3>Exercise</h3>
            <img src="{% static 'meals_app/workout.jpg' %}">
            <h4>Running out of ideas in regards to staying active? Here you go</h4>
            <p ><button id="One_Workout">Click Me</button> to get a random workout.</p>
            <ul id="one_workout_list">
            </ul>
            <form action="{% url 'meals_app:add_workout' %}" method="post">
                {% csrf_token %}
                <input type="date" name="workoutCalDate">
                <input type="time" name="workoutCalTime" value="20:00">
                <p><input type="submit" value="Click"> to add a workout to your google calendar</p>
            </form>
            <script src="{% static 'meals_app/oneWorkout.js' %}"></script>

        </div>

        <div class="col-sm-4">
            <h3>Read</h3>
            <img src="{% static 'meals_app/books.jpg' %}">
            <h4>Be a nerd - read a book.</h4>
            <form action="{% url 'meals_app:add_book' %}" method="post">
                {% csrf_token %}
                <p><input type="date" name="bookStartDate">Start Date</p>
                <p><input type="date" name="bookFinishDate">Finish Date</p>
                <p><input type="time" name="bookReminderTime" value="20:00">Set reminders to this time</p>
                <p><input type="text" name="title"> Title of book?</p>
                <p><input type="number" name="pages" value="250"> Pages in book?</p>
                <p><input type="number" name="reminderFrequency" value="7">Remind me every X number of days.</p>
                <p><input type="submit" value="Click">to add reading goals to your google calendar</p>
            </form>
            <script src="{% static 'meals_app/books.js' %}"></script>


        </div>
    </div>
</div>
{% endblock %}

meals_app/templates/core/singleMeal.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<p>All recipes were gathered from <a href="https://cookieandkate.com/">CookieandKate.com</a>. All are vegetarian and healthy recipes.</p>
<p>Getting a meal idea for the day is simple. Just press the <button>Click me</button> button under the Eat section and you will be provided with one of the over 200 dinner recipes along with how long it should take to make the meal and a shopping list</p>


{% endblock %}

meals_app/templates/core/singleWorkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<p>Most of these Workouts are CrossFit workouts so they may or may not be for you. In the future we may offer different
levels of workouts. For now, if you want to exercise just press the <button>Click me</button> under the Exercise section
    and you will be given a random CrossFit workout to do.</p>
{% endblock%}